### ISSUE TITLE
【译文】在VueJS中漂亮的视觉滚动效果——每日Vue技巧#2

### ISSUE THREAD

**Issue by zjgyb** [zjgyb/my-tutorial#32]
视觉滚动效果是增加设计深度和让你网站更加出色的一种很好的方式。

近来，我受到Webflow视觉滚动的启发，想要在Vue中实现类似的方式。

这是我遇到的内容。

![reason](https://learnvue.co/wp-content/uploads/2020/04/20200402_Parallax-2.gif)

在教程的最后，你将知道如何在[Vue3.0](https://learnvue.co/2019/12/what-does-vuejs-3-0-mean-for-web-development/)中设置视觉滚动效果，然后在你的项目中用你自己的图片更好地使用它。

开始编程！

## Vue视觉滚动效果如何使用

让我们首先搞清楚视觉滚动效果的含义是什么，然后我们如何在[Vue3中使用它](https://learnvue.co/2020/02/building-the-same-component-in-vue2-vs-vue3)。

视觉滚动是当你的背景元素相对于前景元素有一个不同的移动速度——这在屏幕上会创造一个深度感。

为了在Vue中做到这一点，我们将给元素提供两张背景图片，这两张图片将在用户向下滚动页面的时候进行放大。我们也将增加两个不同的页面部分，它们会随着用户滚动而逐渐消失，以便你可以看到我们正在做其他事情。

我们将监听一些滚动事件，之后使用滚动位置，然后元素位置决定哪一个元素可见和它们拥有什么样式。

一旦我们开始编码这会变得更有意义，因此让我们开始吧。

## 新建模板

这是我们在组件模板内的代码。

```vue
<template>
  <div class='root'>
    <img class='background' ref='background' src='../assets/tree-1.jpg'/>
    <img class='foreground' ref='foreground' src='../assets/tree-foreground.png'/>
    <div class='section section-1' ref='first'>
      <div>
        <h1> Parallax Made Easy. </h1>
      </div>
    </div>
    <div class='section section-2' ref='second'>
      <div>
        <h2> Here's more info </h2>
        <p> Lorem ipsum dolor, sit amet consectetur adipisicing elit...</p>
      </div>
    </div>
  </div>
</template>
```

如你所见，我们有……

- 一个包含视差部分根元素
- 2个图片元素——前景和背景
- 2个不同的内容块——包含文本

其它重要需要注意的事是我们给很多元素提供了模板ref，以便能够在脚本中访问它变得容易。

这是我们将使用的两张图片。

背景图（来自：[Unsplash](https://unsplash.com/photos/mERlBKFGJiQ)）

![background](https://learnvue.co/wp-content/uploads/2020/04/tree-1-300x200.jpg)

前景图（来自：[Creative Plannet](http://creativeplannet.blogspot.com/2011/07/creative-page-borders.html)）

![foreground](https://learnvue.co/wp-content/uploads/2020/04/tree-foreground-300x285.png)

## 装饰组件

这是魔法开始的地方。

首先，让我们装饰图片。我们想让它们固定并且占据整个屏幕——因此我们需要花费一点时间来调整它们到我们想要的实际大小。这与你的图片也会不同，只需要尝试把它们放到你认为看起来更好的地方。

```css
img.background, img.foreground {
  /* Fill background */
  min-height: 100%;
  min-width: 1024px;

  /* Scale proportionately */
  width: 100%;
  height: auto;
}

img.background {
  /* Positioning */
  position: fixed;
  top: 0;
  left: 0;
}
```

现在，我们想要装饰section的class——我们需要确保每一个section至少是window大小。

```css
.section {
  min-height: 100vh;
  position: relative;
}
```

其次，我们可以装饰每一个section的内容。我们想让它们固定在顶部通过使用`position: fixed`，然后使用transform居中。

然后，我们想要控制可见的方式是改变透明度，因此我们设置第二个section有一个`opacity: 0`的默认值。

其余部分能够自行理解，只是这些属性我认为让组件看起来更好，当然你可以随意改变任何内容。

```css
.section > div {
  position: fixed;
  color: white;
  /* centers this div */
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}

.section-1 {
  margin-bottom: 500px; /* determines the gap between our two sections */
  font-size: 4em;
}

.section-2 {
  opacity: 0; /* defaults to 0 because it's not visible */
}

.section-2 div {
  background-color: rgba(255, 255, 255, 0.7);
  color: black;
  text-align: center;
  padding: 50px;
  max-width: 300px;
}

.section-2 h2 {
  font-size: 2em;
  margin-bottom: 40px;
}

.section-2 p {
  line-height: 150%;
}
```

现在到这部分，这是我们应该看到的内容。

![show1](https://learnvue.co/wp-content/uploads/2020/04/20200402-Screenshot-1024x493.png)

我们的页面看起来放在一起了，但是如果我们滚动将什么都不会发生，同时Section #2部分将不会显现。

这是因为我们实际上还没有任何视差逻辑，因此让我们开始做吧。

## 增加视觉效果

我们将使用Vue3的[Composition API](https://learnvue.co/2020/01/4-vue3-composition-api-tips-you-should-know/)来实现逻辑，因此首先我们需要做的是从Vue中导入一些东西。同样地，在setup方法内，我们访问模板ref。

```vue
<script>
import { ref, onMounted, onUnmounted } from 'vue'
export default {
  setup () {

    const foreground = ref(null)
    const background = ref(null)
    const first = ref(null)
    const second = ref(null)

    return {
      foreground,
      background,
      first,
      second
    }
  }
}
</script>
```

现在，我们增加和移除滚动监听事件分别在组件挂载和卸载生命钩子时。

```js
onMounted(() => {
  document.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  document.removeEventListener('scroll', handleScroll)
})
```

最后，让我们获取最酷的部分[事件处理方法](https://learnvue.co/2020/01/a-vue-event-handling-cheatsheet-the-essentials)——叫做`handleScroll`。依赖于滚动值，有四件事我们需要改变

1. 首个section的透明度
2. 第二个section的透明度
3. 前景缩放
4. 背景缩放

我们的代码将是这样。

```js
const handleScroll = (evt) => {

  const scrollY = window.scrollY
  // decreases as user scrolls
  first.value.style.opacity = (100 - ((scrollY + window.innerHeight) - first.value.offsetHeight)) / 100
  // increases as user scrolls
  second.value.style.opacity = ((scrollY + window.innerHeight) - second.value.offsetTop) / 100

  const maxBackgroundSize = 120;
  const backgroundSize = ((scrollY) / (maxBackgroundSize - 100)) // increases as user scrolls

  // zoom the background at a slower rate
  background.value.style.transform = 'scale(' + (100 + backgroundSize * .4) / 100 + ')'
  foreground.value.style.transform = 'scale(' + (100 + backgroundSize) / 100 + ')'
}
```

这是我们视差效果，这是我们的应用程序在向下滚动时看起来的效果。

![result](https://learnvue.co/wp-content/uploads/2020/04/20200402_Parallax-2.gif)

有很多不同的拓展你可以在这个项目中增加——更多的section、更多的层、不同的效果。只要你理解了如何让你的样式响应滚动位置，一切都有可能。

这需要花费一些额外的精力来达到你想要的方式，例如图片的特定样式或者变量值，同时为了让它在不同的窗口看起来更加好看需要花费一些额外的工作。

但是现在，我们已经有了我们想要的东西。

## 还有

视觉滚动效果还有许多其他的用途——实际上对于装饰浏览器应用程序是一个响应式的方式，我想看到你想到的内容！

我希望这会如往常一样给你一点想法去实现一些东西，如果你有任何问题，只需要留言。

快乐地编码吧！

## 原文地址

- [传送门](https://learnvue.co/2020/04/a-beautiful-parallax-scrolling-effect-in-vuejs-daily-vue-tips-2/)

## 扩展

1. 原文中没有设置`img.foreground`，如果不设置是有误的

```diff
img.background, img.foreground {
  /* Fill background */
  min-height: 100%;
  min-width: 1024px;

  /* Scale proportionately */
  width: 100%;
  height: auto;
+ position: fixed;
+ top: 0;
+ left: 0;
}

- img.background {
-   /* Positioning */
-   position: fixed;
-   top: 0;
-   left: 0;
- }
```

2. `handleScroll`方法设置两个块的透明度需要改进。
